name: Release Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version (v1.0.0)'
        required: true
        type: string
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Build extension
        run: pnpm build
        
      - name: Package Chrome Extension
        run: |
          echo "Creating Chrome extension package..."
          cd build/chrome-mv3-prod
          zip -r ../../chrome-extension.zip *
          cd ../..
          
      - name: Package Firefox Extension
        run: |
          echo "Creating Firefox extension package..."
          cd build/firefox-mv3-prod || cd build/chrome-mv3-prod
          zip -r ../../firefox-extension.zip *
          cd ../..
          
      - name: List packages
        run: |
          echo "Checking created packages:"
          ls -la *.zip
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            chrome-extension.zip
            firefox-extension.zip
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          body: |
            # Plasmo Extension Release ${{ inputs.version }}
            
            ## Chrome Extension
            - Download the `chrome-extension.zip` file
            - Go to `chrome://extensions/`
            - Enable "Developer mode"
            - Drag and drop the zip file into the extensions page
            
            ## Firefox Extension
            - Download the `firefox-extension.zip` file
            - Go to `about:debugging#/runtime/this-firefox`
            - Click "Load Temporary Add-on"
            - Select the downloaded zip file
            
            This release was automatically generated by GitHub Actions.
          draft: false
          prerelease: false
          generate_release_notes: true 